require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']
  
  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'TimeFit' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )

    installer.aggregate_targets.each do |aggregate_target|
      user_project = aggregate_target.user_project

      user_project.native_targets.each do |native_target|
        next unless native_target.name == 'TimeFit'

        native_target.build_configurations.each do |build_configuration|
          build_settings = build_configuration.build_settings
          build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = podfile_properties['ios.deploymentTarget'] || '16.0'

          framework_paths = build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
          framework_paths = [framework_paths] if framework_paths.is_a?(String)
          framework_path = '$(SRCROOT)/../../../node_modules/react-native-kakao-maps/ios'
          framework_paths << framework_path unless framework_paths.include?(framework_path)
          build_settings['FRAMEWORK_SEARCH_PATHS'] = framework_paths

          other_ldflags = build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
          other_ldflags = other_ldflags.split(' ') if other_ldflags.is_a?(String)
          other_ldflags = other_ldflags.each_with_index.reject do |flag, index|
            flag == 'DaumMap' || (flag == '-framework' && other_ldflags[index + 1] == 'DaumMap')
          end.map(&:first)
          other_ldflags += ['-framework', 'DaumMap']
          build_settings['OTHER_LDFLAGS'] = other_ldflags
        end
      end

      user_project.save
    end
  end
end
