export const APP_ROUTES = {
  beforeStartOnboarding: '/before-start/onboarding',
  beforeStartHome: '/before-start/home',
  beforeStartSearch: '/before-start/search',
  beforeDepartureRecommendation: '/before-departure/recommendation',
  beforeDepartureDetail: '/before-departure/detail',
  beforeDepartureTransitPopup: '/before-departure/transit',
  transitMain: '/in-transit/moving',
  transitArrival: '/in-transit/arrival',
  reengagementRoutines: '/re-engagement/routines',
  reengagementLogin: '/re-engagement/login',
  reengagementSettings: '/re-engagement/settings',
  reengagementRoutineCreate: '/re-engagement/routine-create',
  settingsDepartureNotification: '/re-engagement/settings/departure-notification',
  settingsRoutineNotification: '/re-engagement/settings/routine-notification',
  settingsEmergencyNotification: '/re-engagement/settings/emergency-notification',
  settingsTheme: '/re-engagement/settings/theme',
  settingsAccount: '/re-engagement/settings/account',
  settingsLanguage: '/re-engagement/settings/language',
  settingsUnit: '/re-engagement/settings/unit',
  settingsTimeFormat: '/re-engagement/settings/time-format',
  settingsTerms: '/re-engagement/settings/terms',
  settingsPrivacy: '/re-engagement/settings/privacy',
  settingsHelp: '/re-engagement/settings/help',
  settingsAbout: '/re-engagement/settings/about',

  onboarding: '/onboarding',
  home: '/(tabs)/home',
  routine: '/(tabs)/routine',
  settings: '/(tabs)/settings',
  search: '/search',
  routeRecommend: '/route/recommend',
  routeDetail: '/route/detail',
  testMap: '/test-map',
} as const;

export type AppRoutePath = (typeof APP_ROUTES)[keyof typeof APP_ROUTES];
