#!/usr/bin/env node

/*
 * node scripts/parseGtfsShapes.js
 *
 * 1) data/gtfs/shapes.txt 파싱
 * 2) data/gtfs/shape-line-map.json 매핑 적용 (shape_id -> lineName)
 * 3) apps/mobile/src/data/subwayLineGeometry.ts 자동 생성
 */

const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const SHAPES_PATH = path.join(ROOT, 'data/gtfs/shapes.txt');
const MAP_PATH = path.join(ROOT, 'data/gtfs/shape-line-map.json');
const OUT_PATH = path.join(ROOT, 'apps/mobile/src/data/subwayLineGeometry.ts');

const DEFAULT_LINE_COLORS = {
  '1호선': '#0052A4',
  '2호선': '#00A84D',
  '3호선': '#EF7C1C',
  '4호선': '#00A4E3',
  '5호선': '#996CAC',
  '6호선': '#CD7C2F',
  '7호선': '#747F00',
  '8호선': '#E6186C',
  '9호선': '#BDB092',
  수인분당선: '#F5A200',
  신분당선: '#D31145',
  경의중앙선: '#77C4A3',
  경춘선: '#0C8E72',
  공항철도: '#0090D2',
};

if (!fs.existsSync(SHAPES_PATH)) {
  throw new Error(`shapes.txt not found: ${SHAPES_PATH}`);
}

const shapeMap = fs.existsSync(MAP_PATH) ? JSON.parse(fs.readFileSync(MAP_PATH, 'utf-8')) : {};
const shapeMapKeys = new Set(Object.keys(shapeMap));

const content = fs.readFileSync(SHAPES_PATH, 'utf-8').replace(/\r/g, '');
const lines = content.split('\n');
const header = lines[0].split(',').map((v) => v.trim());

const idxShapeId = header.indexOf('shape_id');
const idxLat = header.indexOf('shape_pt_lat');
const idxLng = header.indexOf('shape_pt_lon');
const idxSeq = header.indexOf('shape_pt_sequence');

if ([idxShapeId, idxLat, idxLng, idxSeq].some((v) => v < 0)) {
  throw new Error('invalid shapes header: shape_id/shape_pt_lat/shape_pt_lon/shape_pt_sequence required');
}

const byShape = new Map();

for (let i = 1; i < lines.length; i += 1) {
  const row = lines[i].trim();
  if (!row) continue;

  const cols = row.split(',');
  const shapeId = cols[idxShapeId];
  const lat = Number(cols[idxLat]);
  const lng = Number(cols[idxLng]);
  const seq = Number(cols[idxSeq]);

  if (!shapeId || Number.isNaN(lat) || Number.isNaN(lng) || Number.isNaN(seq)) {
    continue;
  }

  if (!byShape.has(shapeId)) {
    byShape.set(shapeId, []);
  }

  byShape.get(shapeId).push({ seq, latitude: lat, longitude: lng });
}

const byLine = {};
for (const lineName of Object.keys(DEFAULT_LINE_COLORS)) {
  byLine[lineName] = [];
}

for (const [shapeId, points] of byShape.entries()) {
  if (!shapeMapKeys.has(shapeId)) {
    continue;
  }

  const lineName = shapeMap[shapeId];
  if (!byLine[lineName]) {
    byLine[lineName] = [];
  }

  points.sort((a, b) => a.seq - b.seq);
  byLine[lineName].push(...points.map((p) => ({ latitude: p.latitude, longitude: p.longitude })));
}

const dedup = (arr) => {
  const out = [];
  let prev = null;
  for (const p of arr) {
    const key = `${p.latitude.toFixed(6)},${p.longitude.toFixed(6)}`;
    if (key === prev) continue;
    out.push(p);
    prev = key;
  }
  return out;
};

for (const key of Object.keys(byLine)) {
  byLine[key] = dedup(byLine[key]);
}

const file = `import { LatLng } from '../services/routeGeometry/types';

/**
 * Auto-generated by scripts/parseGtfsShapes.js
 * Source: data/gtfs/shapes.txt
 */
export const SUBWAY_LINE_GEOMETRY: Record<string, LatLng[]> = ${JSON.stringify(byLine, null, 2)};

export const SUBWAY_LINE_COLORS: Record<string, string> = ${JSON.stringify(DEFAULT_LINE_COLORS, null, 2)};
`;

fs.writeFileSync(OUT_PATH, file, 'utf-8');
console.log(`generated: ${OUT_PATH}`);
